apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-doknotstatus-converter
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 64Mi
  kafka:
    pool: nav-prod
  env:
    - name: BRUKERVARSEL_TOPIC
      value: min-side.brukervarsel-v1
    - name: DOKNOTIFIKASJON_STATUS_TOPIC
      value: teamdokumenthandtering.aapen-dok-notifikasjon-status
    - name: GROUP_ID_DOKNOTIFIKASJON_STATUS
      value: prod-tms-doknotstatus-mottak-1
